# Generated by Django 6.0.2 on 2026-03-31 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=50)),
                ('date_exam', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(max_length=50)),
                ('nb_etudiants', models.IntegerField(default=30)),
                ('nb_surveillants_requis', models.IntegerField(default=1)),
                ('enseignant_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_responsable', to='users.enseignant')),
            ],
            options={
                'ordering': ['date_exam', 'heure_debut'],
            },
        ),
    ]
