# Generated by Django 6.0.2 on 2026-03-31 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examens', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('responsable', 'Responsable de matière'), ('surveillant', 'Surveillant'), ('remplacant', 'Remplaçant')], default='surveillant', max_length=20)),
                ('present', models.BooleanField(default=True)),
                ('motif_absence', models.TextField(blank=True)),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveillances', to='users.enseignant')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveillants', to='examens.examen')),
            ],
            options={
                'unique_together': {('enseignant', 'examen')},
            },
        ),
        migrations.CreateModel(
            name='Absenteisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('heures_reportees', models.FloatField()),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='users.enseignant')),
                ('surveillance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='absenteisme', to='surveillances.surveillance')),
            ],
        ),
    ]
